// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpYtU2WYcvrxnOhh5MCw5QnA0n7VRGVAY',
    appId: '1:877787558762:web:98b34eb5ad0477a917eb13',
    messagingSenderId: '877787558762',
    projectId: 'cselogin-29444',
    authDomain: 'cselogin-29444.firebaseapp.com',
    storageBucket: 'cselogin-29444.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAea8dzFo0n7wPyHQGUR2lEgnTN_-WRVaI',
    appId: '1:877787558762:android:a5991c4d0611858117eb13',
    messagingSenderId: '877787558762',
    projectId: 'cselogin-29444',
    storageBucket: 'cselogin-29444.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKUDdVuY89SkyVs4pWn_LeFEG98vyK4Pk',
    appId: '1:877787558762:ios:48e64a84f78e659817eb13',
    messagingSenderId: '877787558762',
    projectId: 'cselogin-29444',
    storageBucket: 'cselogin-29444.appspot.com',
    iosClientId: '877787558762-6rbpvr05agj6dmg1fl71ofj7esjoj9rc.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKUDdVuY89SkyVs4pWn_LeFEG98vyK4Pk',
    appId: '1:877787558762:ios:48e64a84f78e659817eb13',
    messagingSenderId: '877787558762',
    projectId: 'cselogin-29444',
    storageBucket: 'cselogin-29444.appspot.com',
    iosClientId: '877787558762-6rbpvr05agj6dmg1fl71ofj7esjoj9rc.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginUi',
  );
}